// <auto-generated />
using System;
using CattleFarmAPI.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CattleFarmBackend.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230614013512_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CattleFarmAPI.Models.Cattle", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Cattles");
                });

            modelBuilder.Entity("CattleFarmAPI.Models.CattleFeed", b =>
                {
                    b.Property<int>("CattleFeedCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CattleFeedCode"));

                    b.Property<int>("CattleCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FoodQuantity")
                        .HasColumnType("float");

                    b.HasKey("CattleFeedCode");

                    b.ToTable("CattleFeeds");
                });

            modelBuilder.Entity("CattleFarmAPI.Models.CattleMed", b =>
                {
                    b.Property<int>("CattleMedCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CattleMedCode"));

                    b.Property<int>("CattleCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("MedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MedQuantity")
                        .HasColumnType("float");

                    b.HasKey("CattleMedCode");

                    b.ToTable("CattleMeds");
                });
#pragma warning restore 612, 618
        }
    }
}
